import { User, Guild } from "./util/interface";

export const users: User[] = [
  {
    id: 61,
    username: null,
    address: "0x7571a2454e76b2b47ea201dbf86778ab0970ce4c",
    bio: null,
    twitterHandle: null,
    instagramHandle: null,
    websiteUrl: null,
    discordUrl: "cheewengg#3540",
    totalKidnappedCount: 0,
    totalUrsaKidnappedCount: 0,
    totalMinoKidnappedCount: 0,
    totalKidnapCount: 0,
    totalUrsaKidnapCount: 0,
    totalMinoKidnapCount: 0,
    totalHunyClaimed: "0",
    refineryHunyClaimed: "0",
    guildId: 116,
    level: null,
  },
  {
    id: 61,
    username: null,
    address: "0x7571a2454e76b2b47ea201dbf86778ab0970ce4d",
    bio: null,
    twitterHandle: null,
    instagramHandle: null,
    websiteUrl: null,
    discordUrl: "cheewengg#3647",
    totalKidnappedCount: 0,
    totalUrsaKidnappedCount: 0,
    totalMinoKidnappedCount: 0,
    totalKidnapCount: 0,
    totalUrsaKidnapCount: 0,
    totalMinoKidnapCount: 0,
    totalHunyClaimed: "0",
    refineryHunyClaimed: "0",
    guildId: 117,
    level: null,
  },
];

export const guilds: Guild[] = [
  {
    id: 116,
    name: "myCoolGuild",
    leaderAddress: "0x7571a2454e76b2b47ea201dbf86778ab0970ce4c",
    commanderAddresses: [],
    guildLevel: 1,
    guildCrestId: 119,
    guildCrest: {
      colour: "blue",
      design: 2,
    },
    guildSigil: {
      name: "Guardian",
      colour: "purple",
      design: 2,
    },
    guildBanner: {
      colour: "blue",
      design: 2,
    },
    description: "hello world",
    maxCapacity: 20,
    currentSize: 1,
    crestImageId: null,
    crestImageUrl: null,
  },
  {
    id: 117,
    name: "myCoolerGuild",
    leaderAddress: "0x7571a2454e76b2b47ea201dbf86778ab0970ce4c",
    commanderAddresses: [],
    guildLevel: 1,
    guildCrestId: 119,
    guildCrest: {
      colour: "blue",
      design: 2,
    },
    guildSigil: {
      name: "Guardian",
      colour: "purple",
      design: 2,
    },
    guildBanner: {
      colour: "blue",
      design: 2,
    },
    description: "hello world",
    maxCapacity: 20,
    currentSize: 1,
    crestImageId: null,
    crestImageUrl: null,
  },
];
